language: java
jdk:
  - openjdk7
  - oraclejdk8

before_install:
  - cp ./settings.xml ~/.m2/

after_success:
  - mvn clean test jacoco:report coveralls:jacoco

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#lightblue"
    on_success: always
